---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: restore-packages
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: build
          command: npm run build

      - run:
          name: test
          command: npm test

  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm run publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
