---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

      - run:
          name: build
          command: npm run build

      - run:
          name: test
          command: npm test

  build-coverage:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: test
          command: npm test

      - run:
          name: coverage
          command: |
            npm install -g --silent codecov
            codecov -f packages/charts/coverage/*.json

  build-docs:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: build docs
          command: npm run docs

      - persist_to_workspace:
          root: docs
          paths:
            - ./*

  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: restore-packages
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm run publish

  deploy-docs:
    docker:
      - image: node:10.15
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "62:98:5d:aa:44:4f:aa:62:e8:88:04:3d:38:1e:4d:4b"
      - attach_workspace:
          at: docs
      - run:
          name: Deploy documentation
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@reactivemarkets.com"
            git config user.name "ci-build"
            gh-pages --message "docs: updating from ${CIRCLE_SHA1} [skip ci]" --dist docs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-coverage:
          filters:
            branches:
              only: master
      - build-docs:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-docs:
          requires:
            - build-docs
          filters:
            branches:
              only: master
