---
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "markmcdowell"
    commit_message:
      prefix: "chore"
      include_scope: true
    version_requirement_updates: "increase_versions"
